### ISSUE TITLE
build command does not create SNS topic for push notification.

### ISSUE THREAD

**Issue by scottgutman** [uecode/qpush-bundle#113]
First thanks for an awesome bundle.

I am new to AWS SQS.  After installing  qpush in my symfony app, I was able to test the dev environment with uecode:qpush:publish and receive.

After publishing the app to the production server, I am not sure what I need to do next to make qpush work with push notifications.

I tried to manually setup the queue not realising that there was a command.  I also did not know that I needed to create an AWS SNS Topic and subscribe to it.
Then I found this command:
php app/console uecode:qpush:build

It created the SQS queue, but did not create the SNS topic.
i tried to repeat the process by destroy and build again, but  I am not having any luck with creating the SNS topic or subscriptions.
```
config.yml
uecode_qpush:
    logging_enabled: true
    providers:
        aws:
            key:   removed
            secret: removed
            region: us-west-2
            driver: aws
    queues:
        director:
            provider: aws 
            options:
                queue_name: director #optional. the queue name used on the provider
                push_notifications: true
                subscribers:
                    - { endpoint: https://t.starstarmobile.com/, protocol: https }
```

I also have this error in my log:

> [2016-09-23 13:33:16] php.DEBUG: include(/home/tstarsta/app/cache/dev/qpush/30/446f637472696e654e616d65737061636543616368654b65795b5dqpush.php): failed to open stream: No such file or directory {"type":2,"file":"/home/tstarsta/vendor/doctrine/cache/lib/Doctrine/Common/Cache/PhpFileCache.php","line":112,"level":28928} []

Can you help me troubleshoot?
