### ISSUE TITLE
Subscriber don't handle AWS SNS message

### ISSUE THREAD

**Issue by Nicorr** [uecode/qpush-bundle#115]
Hello! 

I'm trying to use the bundle: My problem: **The event does not seems to be catched when receiving a notification**: The processing in my service is not performed.

```
class AsyncService
{
    public function onMessageReceived(MessageEvent $event)
    {
        // do some processing
    }
}
```

The notification is correctly sent, as I verified in the access_log:

"POST / HTTP/1.1" 200 45 "-" "Amazon Simple Notification Service Agent"

config.yml:

```
uecode_qpush:
providers:
    aws:
        driver: aws
        key: '%aws_access_key%'
        secret: '%aws_secret%'
        region: eu-central-1
queues:
    civbq:
        provider: aws
        options:
            queue_name: myqueuename
            push_notifications: true
            subscribers:
                - { endpoint: https://my-site.com/, protocol: https }
```

services.yml:

```
async_service:
    class: AppBundle\Service\AsyncService
    arguments: [@doctrine.orm.entity_manager, @uecode_qpush]
    tags:
        - { name: uecode_qpush.event_listener, event: myqueuename.message_received, method: onMessageReceived }
```

Do you have any suggestions?

Thanks a lot

**Comment by kmfk** [comment]
@Nicorr For `event` on the tag on your service, can you please try changing that to the top level key of the queue in your list of queues, ie:

```
async_service:
    class: AppBundle\Service\AsyncService
    arguments: [@doctrine.orm.entity_manager, @uecode_qpush]
    tags:
        - { name: uecode_qpush.event_listener, event: civbq.message_received, method: onMessageReceived }
```

**Comment by Nicorr** [comment]
@kmfk : Yes, its already the case (I forgot to rename it in the example)

The actual code is:

```
    async_service:
        class: AppBundle\Service\AsyncService
        arguments: [@doctrine.orm.entity_manager, @uecode_qpush]
        tags:
            - { name: uecode_qpush.event_listener, event: civbq.message_received, method: onMessageReceived }
```
