### ISSUE TITLE
What means the subscribers in the config 

### ISSUE THREAD

**Issue by krvajalmiguelangel** [uecode/qpush-bundle#119]
In the configuration there is a node called subscribers. I cant found any reference of what they are and where they come from

**Comment by kmfk** [comment]
Sorry to not get back to you sooner.  In case you're still interested:

Subscribers are typically the HTTP Endpoints (or occasionally email addresses) you want the pushed queue items to go to.

```
queues:
  my_queue_name:
    provider: my_provider
      options:
        push_notifications: true
        subscribers:
          - { endpoint: http://example.com/qpush, protocol: http }
```

Given that example, when a job is queued, the `http://example.com/qpush` endpoint will receive an event with details of the job.  

Typically your subscribers would be a Symfony app with this bundle installed - that will automatically catch the job event and push the job to your tagged services.
